---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/influxd version
    register: influxdb2_test_output
  - name: influxd version
    debug:
      msg: '{{ influxdb2_test_output.stdout }}'
