---
- include_vars:
    file: install-app-vars.yml
- name: check for install at {{ influxdb2_install_subdir }}
  become: true
  become_user: root
  stat:
    path: '{{ influxdb2_install_subdir }}'
  changed_when: false
  register: influxdb2_binary
- when: not influxdb2_binary.stat.exists
  block:
    - name: downloading {{ influxdb2_url }} to {{ influxdb2_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ influxdb2_url }}'
        dest: '{{ influxdb2_tmp_archive }}'
        checksum: '{{ influxdb2_checksum }}'
    - name: mkdir {{ influxdb2_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ influxdb2_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ influxdb2_tmp_archive }} to {{ influxdb2_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ influxdb2_tmp_archive }}'
        dest: '{{ influxdb2_install_dir }}'
        creates: '{{ influxdb2_install_subdir }}'
  always:
    - name: rm {{ influxdb2_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ influxdb2_tmp_archive }}'
        state: absent
- name: linking {{ influxdb2_install_link }} to {{ influxdb2_install_exe }}
  become: true
  become_user: root
  file:
    src: '{{ influxdb2_install_exe }}'
    dest: '{{ influxdb2_install_link }}'
    state: link
